// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vetvduzhvpuvherifqxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldHZkdXpodnB1dmhlcmlmcXhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTgyODEsImV4cCI6MjA2NDU3NDI4MX0.MpaHNsWITTlz4zziWHM-m9jTxILhUOCjE9LyyG4pqqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);